name: CI
on: push

jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build website
        run: npm run build

  lint:
    name: Lint Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          VALIDATE_NATURAL_LANGUAGE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
