name: CI
on: push

jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Assert Types
        run: npm run check-types

      - name: Assert Types
        run: npm run lint

      - name: Build website
        run: npm run build
